name: push to hatena blog

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "entries/**"

jobs:
  push:
    if: |
      github.event.pull_request.merged == true
      && !startsWith(github.head_ref, 'from-draft-to-publish')
      && !startsWith(github.head_ref, 'initialize')
      && !startsWith(github.head_ref, 'blogsync-pull')
    uses: hatena/hatenablog-workflows/.github/workflows/push.yaml@v1
    with:
      local_root: "entries"
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
